# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Design Portfolio
email: csenkisandor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Freelance web designer and developer, specialising in Jekyll, HTML, CSS and JavaScript
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

twitter_username: cssandor
github_username:  cssandor
google_username:  csenkisandor

permalink: /:categories/:title

links:
  - title: about
    url: /about
  - title: work
    url: /work
  - title: articles
    url: /articles
  - title: hire me
    url: /hire-me

# Build settings
markdown: kramdown
